'use client';

/**
 * The fonts offered for title clips.
 *
 * These used to be pulled in by an `@import url(fonts.googleapis.com...)` at
 * the top of globals.css. That silently did nothing in production: Next
 * concatenates the `@font-face` blocks generated by next/font ahead of
 * globals.css, and a CSS `@import` is only valid before any other rule, so the
 * bundled stylesheet dropped it. The picker offered fifteen fonts and every one
 * of them rendered as the fallback.
 *
 * Loading it as a real <link> fixes that — and doing it on demand means a user
 * who never adds a title never pays for it, which on a phone is the common case.
 */

const STYLESHEET_ID = 'mvp-title-fonts';

const FAMILIES = [
  'Bebas+Neue',
  'Caveat:wght@400;700',
  'DM+Sans:wght@400;600;700',
  'Fira+Sans:wght@400;600;700',
  'Inter:wght@400;500;600;700',
  'Lora:wght@400;600;700',
  'Merriweather:wght@400;700',
  'Montserrat:wght@400;600;700',
  'Nunito:wght@400;600;700',
  'Oswald:wght@400;500;600',
  'Playfair+Display:wght@400;600;700',
  'Poppins:wght@400;500;600;700',
  'Roboto+Mono:wght@400;500;700',
  'Space+Grotesk:wght@400;500;700',
  'Source+Serif+4:wght@400;600;700',
];

export const TITLE_FONTS_HREF =
  `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;

/** Add the stylesheet once. Safe to call on every render. */
export function ensureTitleFontsLoaded(doc: Document = document): void {
  if (doc.getElementById(STYLESHEET_ID)) return;
  const link = doc.createElement('link');
  link.id = STYLESHEET_ID;
  link.rel = 'stylesheet';
  link.href = TITLE_FONTS_HREF;
  doc.head.appendChild(link);
}
