"""
Vendor instrument silhouettes from game-icons.net (CC BY 3.0).

Five hand-built attempts at drawing a violin, a saxophone and a brass instrument
were rejected. These are drawn by actual illustrators, they are open licensed,
and they are single-path monochrome silhouettes - which is exactly the shape of
art that survives at card size. Attribution is required by CC BY 3.0 and is
recorded in public/icons/instruments/ATTRIBUTION.md.

Stored as raw path data in a TS module so they render as inline SVG with no
network request and can be tinted by CSS.
"""
import io
import json
import os
import re
import urllib.request

RAW = "https://raw.githubusercontent.com/game-icons/icons/master/"

# our instrument id -> (game-icons path, author)
ICONS = {
    'violin':        ('zajkonur/violin.svg', 'Zajkonur'),
    'cello':         ('zajkonur/violin.svg', 'Zajkonur'),
    'contrabass':    ('zajkonur/violin.svg', 'Zajkonur'),
    'harp':          ('delapouite/harp.svg', 'Delapouite'),
    'saxophone':     ('delapouite/saxophone.svg', 'Delapouite'),
    'flute':         ('delapouite/flute.svg', 'Delapouite'),
    'clarinet':      ('caro-asercion/clarinet.svg', 'Caro Asercion'),
    'bassoon':       ('caro-asercion/bassoon.svg', 'Caro Asercion'),
    'trumpet':       ('delapouite/trumpet.svg', 'Delapouite'),
    'trombone':      ('caro-asercion/trombone.svg', 'Caro Asercion'),
    'french-horn':   ('caro-asercion/french-horn.svg', 'Caro Asercion'),
    'tuba':          ('caro-asercion/tuba.svg', 'Caro Asercion'),
    'xylophone':     ('delapouite/xylophone.svg', 'Delapouite'),
    'marimba':       ('delapouite/xylophone.svg', 'Delapouite'),
    'vibraphone':    ('delapouite/xylophone.svg', 'Delapouite'),
    'glockenspiel':  ('delapouite/xylophone.svg', 'Delapouite'),
    'tubular-bells': ('delapouite/xylophone.svg', 'Delapouite'),
}

PATH_RE = re.compile(r'<path[^>]*\sd="([^"]+)"', re.I)
VIEWBOX_RE = re.compile(r'viewBox="([^"]+)"', re.I)


def fetch(path):
    req = urllib.request.Request(RAW + path, headers={"User-Agent": "musicvid-pro"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8")


def main():
    out = {}
    authors = {}
    cache = {}
    for iid, (path, author) in ICONS.items():
        if path not in cache:
            svg = fetch(path)
            # game-icons wrap the glyph in a background rect + the shape path;
            # the LAST path is the instrument, the first is the square backdrop.
            paths = PATH_RE.findall(svg)
            if not paths:
                print(f"  !! no path in {path}")
                continue
            d = max(paths, key=len)  # the instrument outline is the long one
            vb = VIEWBOX_RE.search(svg)
            cache[path] = (d, vb.group(1) if vb else '0 0 512 512')
            print(f"  {path}: path {len(d)} chars, viewBox {cache[path][1]}")
        out[iid] = cache[path]
        authors[path] = author

    os.makedirs('lib/midi', exist_ok=True)
    lines = [
        '// lib/midi/instrumentIcons.ts',
        '// GENERATED by scripts/fetch-instrument-icons.py - do not hand-edit.',
        '//',
        '// Instrument silhouettes from game-icons.net, CC BY 3.0. Five hand-built',
        '// attempts at drawing these were rejected; these are drawn by illustrators.',
        '// Attribution: public/icons/instruments/ATTRIBUTION.md',
        '',
        'export interface InstrumentIcon { d: string; viewBox: string }',
        '',
        'export const INSTRUMENT_ICONS: Record<string, InstrumentIcon> = {',
    ]
    for iid, (d, vb) in sorted(out.items()):
        lines.append(f"  '{iid}': {{ viewBox: '{vb}', d: '{d}' }},")
    lines.append('};')
    lines.append('')
    lines.append('export function iconFor(id: string): InstrumentIcon | null {')
    lines.append('  return INSTRUMENT_ICONS[id] ?? null;')
    lines.append('}')
    lines.append('')
    io.open('lib/midi/instrumentIcons.ts', 'w', encoding='utf-8').write('\n'.join(lines))
    print(f"wrote lib/midi/instrumentIcons.ts with {len(out)} icons")

    os.makedirs('public/icons/instruments', exist_ok=True)
    att = ['# Instrument silhouette attribution', '',
           'Instrument silhouettes are from [game-icons.net](https://game-icons.net),',
           'used under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/).',
           'They are embedded as path data in `lib/midi/instrumentIcons.ts`.', '',
           '| Icon | Author |', '|---|---|']
    for path, author in sorted(authors.items()):
        att.append(f'| `{path}` | {author} |')
    att.append('')
    io.open('public/icons/instruments/ATTRIBUTION.md', 'w', encoding='utf-8').write('\n'.join(att))
    print('wrote attribution')


if __name__ == '__main__':
    main()
